spring:
    profiles:
       active: dev
    http:
       multipart:
          max-file-size: 5MB
          max-request-size: 5MB
    jackson:
       time-zone: GMT+8
       date-format: yyyy-MM-dd HH:mm:ss
config:
    queue:
        miniappPush: false
        appPush: false
        userScore: false
        formId: false