spring:
    profiles:
       active: dev
    http:
       multipart:
          max-file-size: 500MB
          max-request-size: 500MB
config:
    queue:
        miniappPush: false
        appPush: true
        userScore: true
        formId: false